Db update
TeamRocketBalleBalle/RICA-Remastered pull request #78
Opened 2021-11-23 04:52 UTC by Ya-s-h

Change in location of RoguedBear and Lorem Ipsum...

2021-11-23 05:12 UTC, RoguedBear requested changes

2021-11-23 05:12 UTC, RoguedBear commented on backend/database/testdata.sql
> +(1,"patient", "Roguedbear", "gonerogued@gmail.com", "Aligarh","1234567899", 'pbkdf2:sha256:260000$2lZe7hIHIKzN1XqW$2ef1d75eb5fb593b2eff8d76eaf0df216dea5c577b504a2696d25931f0cf59c9'),
i said NO

2021-11-29 08:40 UTC, Ya-s-h commented on backend/database/testdata.sql
> +(1,"patient", "Roguedbear", "gonerogued@gmail.com", "Aligarh","1234567899", 'pbkdf2:sha256:260000$2lZe7hIHIKzN1XqW$2ef1d75eb5fb593b2eff8d76eaf0df216dea5c577b504a2696d25931f0cf59c9'),
but why bro
@RoguedBear

2021-11-29 08:40 UTC, Ya-s-h commented on backend/database/testdata.sql
> +(1,"patient", "Roguedbear", "gonerogued@gmail.com", "Aligarh","1234567899", 'pbkdf2:sha256:260000$2lZe7hIHIKzN1XqW$2ef1d75eb5fb593b2eff8d76eaf0df216dea5c577b504a2696d25931f0cf59c9'),
that was meant as a joke

2021-11-30 11:34 UTC, closed without merging